baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Arun Gupta"

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"
canonifyURLs = true

[params]
  # FeelIt theme version
  version = "1.0.X"
  # site description
  description = "Resources for aspiring QA Engineers"
  # site keywords
  keywords = ["QA", "Software", "Testing", "Development", "Quality Assurance", "Quality Engineering"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  #date format
  dateFormat = "2006-01-02"

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "QA In Progress"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

[params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
       avatarURL = "/images/site default/avatar.svg"
      title = ""

      # subtitle shown in home page
      subtitle = "Learn | Code | Test"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true

    [params.about]
    # whether to enable profile on about page
    # depends on .Site.Params.home.profile.enable
    enable = true
    # whether to enable param layout
    param = true
    # title for param layout
    paramTitle = "Technical Skills"
    # general description of your site
    # can be write with markdown style
    description = "A seasoned SDET with over a decade of experience working with Selenium WebDriver, TestNG, JUnit, Cucumber, Rest Assured and other Java based libraries. Also, an avid stock market observer and learner. Loves sharing knowledge by writing technical blogs. Currently automating a complex logistics platform and reading Super Trader by Van Tharp."
    # description of your status
    [[params.about.status]]
      faIcon = "fa-solid fa-building"
      title = "Company"
      desc = "Sprinklr"
    [[params.about.status]]
      faIcon = "fa-solid fa-briefcase fa-fw"
      title = "Position"
      desc = "Lead Automation Engineer"
    [[params.about.status]]
      title = "Location"
      faIcon = "fa-solid fa-map-marker-alt"
      desc = "India"
    # description of your parameter
    [[params.about.parameter]]
      language = "Java"
      level = "70"
    [[params.about.parameter]]
      language = "Selenium WebDriver (UI Automation)"
      level = "80"
    [[params.about.parameter]]
      language = "REST-Assured (Backend Automation)"
      level = "60"


  [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
    #display image-preview
      imagePreview = true
    # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "agupta3690"
    Linkedin = "agupta3690"
    Twitter = "gupta_arun"
    Youtubechannel = "UCSGF9T6fpXQsvPeaJ2QiD-Q"
    Quora = ""
    Email = "arun.gupta36@yahoo.com"
    Resume = ""

   # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # FeelIt NEW | 0.2.0

   #Footer config
  [params.footer]
    enable = true
    # FeelIt NEW | 0.2.0
# Custom content (HTML format is supported)
    custom = ''
    # FeelIt NEW | 0.2.0
 #whether to show Hugo and theme info
    hugo = false
    # FeelIt NEW | 0.2.0
 #whether to show copyright info
    copyright = false

 #Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "QA In Progress"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = "<span style='color:#00cc00'>&#10003;<span>"
      # FeelIt NEW | 0.2.5
 #whether to use typeit animation for title name
      typeit = false
      # FeelIt NEW | 1.0.0
 #whether to show RSS icon
      rss = true

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = true
      Tumblr = true
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = true
   

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

  [params.page.toc]
      # whether to enable the table of the contents
      enable = false
# whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = false

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false
